services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=bluecomet
      - POSTGRES_DB=merolastation
    ports:
      - "5432:5432" #Only for local development, remove this line when deploying to AWS
    networks:
      - merolastation-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:bluecomet@postgres:5432/merolastation?sslmode=disable
    depends_on:
      - postgres
    networks:
      - merolastation-network
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: [ "/app/main" ]
    
networks:
  merolastation-network: