// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: collection_train.sql

package db

import (
	"context"
)

const createCollectionTrain = `-- name: CreateCollectionTrain :one
INSERT INTO collection_trains (
  user_id,
  train_id
) VALUES (
  $1, $2
) RETURNING id, user_id, train_id, created_at
`

type CreateCollectionTrainParams struct {
	UserID  int64 `json:"user_id"`
	TrainID int64 `json:"train_id"`
}

func (q *Queries) CreateCollectionTrain(ctx context.Context, arg CreateCollectionTrainParams) (CollectionTrain, error) {
	row := q.db.QueryRowContext(ctx, createCollectionTrain, arg.UserID, arg.TrainID)
	var i CollectionTrain
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrainID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCollectionTrain = `-- name: DeleteCollectionTrain :exec
DELETE from collection_trains WHERE user_id = $1 AND train_id = $2
`

type DeleteCollectionTrainParams struct {
	UserID  int64 `json:"user_id"`
	TrainID int64 `json:"train_id"`
}

func (q *Queries) DeleteCollectionTrain(ctx context.Context, arg DeleteCollectionTrainParams) error {
	_, err := q.db.ExecContext(ctx, deleteCollectionTrain, arg.UserID, arg.TrainID)
	return err
}

const getUserCollectionTrains = `-- name: GetUserCollectionTrains :many
SELECT id, user_id, train_id, created_at FROM collection_trains
WHERE user_id = $1
LIMIT $2
OFFSET $3
`

type GetUserCollectionTrainsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetUserCollectionTrains(ctx context.Context, arg GetUserCollectionTrainsParams) ([]CollectionTrain, error) {
	rows, err := q.db.QueryContext(ctx, getUserCollectionTrains, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectionTrain{}
	for rows.Next() {
		var i CollectionTrain
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrainID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionTrains = `-- name: ListCollectionTrains :many
SELECT id, user_id, train_id, created_at FROM collection_trains
ORDER BY user_id
LIMIT $1
OFFSET $2
`

type ListCollectionTrainsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCollectionTrains(ctx context.Context, arg ListCollectionTrainsParams) ([]CollectionTrain, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionTrains, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectionTrain{}
	for rows.Next() {
		var i CollectionTrain
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrainID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
