// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"time"
)

type CollectionTrain struct {
	UserID    int64     `json:"user_id"`
	TrainID   int64     `json:"train_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Train struct {
	ID          int64     `json:"id"`
	ModelNumber string    `json:"model_number"`
	Name        string    `json:"name"`
	Value       int64     `json:"value"`
	Version     int64     `json:"version"`
	CreatedAt   time.Time `json:"created_at"`
}

type User struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}

type WishlistTrain struct {
	UserID    int64     `json:"user_id"`
	TrainID   int64     `json:"train_id"`
	CreatedAt time.Time `json:"created_at"`
}
