name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:alpine
          env:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: bluecomet
            POSTGRES_DB: MerolaStation
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/migrate
        which migrate

    - name: Add citext extension to Postgres
      run: |
        PGPASSWORD=bluecomet psql -h localhost -U root -d MerolaStation -c "CREATE EXTENSION IF NOT EXISTS citext;"
        

    - name: Install PostgreSQL client
      run: sudo apt-get -yqq install postgresql-client
  
    - name: Wait for PostgreSQL to start
      run: |
        until PGPASSWORD=bluecomet psql -h localhost -U root -d merola_station -c '\q'; do
        echo "Postgres is unavailable - sleeping"
        sleep 1
        done


    - name: Run migrations
      run: make migrateup
  
    - name: Test
      run: make test